package com.hub.models;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * This class represents the franchise that a user belongs to.  It is a basic class with a simple function of providing
 * the name and location of the user's franchise, that's all.
 * Created by Doug Heinbokel on 1/31/19
 */
@Entity
@Table(name = "FRANCHISE")
public class Franchise {

    /**
     * These are the fields for the Franchise class.  The Id and GeneratedValue annotations tell Spring that the frID
     * is the id for the entity and that the id will be auto generated by the database upon addition to the database.
     * An id will not be required when creating a new location, only the frName and frLocation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "FRANCHISE_ID")
    private Integer frID;
    @Column(name = "NAME")
    private String frName;
    @Column(name = "LOCATION")
    private String frLocation;
    @OneToMany
    @JoinColumn(name = "FRANCHISE_ID", referencedColumnName = "FRANCHISE_ID")
    private List<HubUser> hubUsers = new ArrayList<>();

    /**
     * A simple default constructor for the Franchise class.
     */
    Franchise(){

    }

    /**
     * Getters and setters for the Franchise class.
     */
    public Integer getFrID() {
        return frID;
    }

    public void setFrID(Integer frID) {
        this.frID = frID;
    }

    public String getFrName() {
        return frName;
    }

    public void setFrName(String frName) {
        this.frName = frName;
    }

    public String getFrLocation() {
        return frLocation;
    }

    public void setFrLocation(String frLocation) {
        this.frLocation = frLocation;
    }

    public List<HubUser> getHubUsers() {
        return hubUsers;
    }

    public void setHubUsers(List<HubUser> hubUsers) {
        this.hubUsers = hubUsers;
    }
}
