package com.hub.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * This class represents the franchise that a user belongs to.  It is a basic class with a simple function of providing
 * the name and location of the user's franchise, that's all.
 * Created by Doug Heinbokel on 1/31/19
 */
@Entity
@Table(name = "FRANCHISE")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Franchise {

    /**
     * These are the fields for the Franchise class.  The Id and GeneratedValue annotations tell Spring that the frID
     * is the id for the entity and that the id will be auto generated by the database upon addition to the database.
     * An id will not be required when creating a new location, only the frName and frLocation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "FRANCHISE_ID")
    private Integer frID;

    @Column(name = "NAME")
    private String frName;

    @Column(name = "LOCATION")
    private String frLocation;

    @Column(name = "ACTIVE")
    private boolean isActive;

    @OneToMany
    @JoinColumn(name = "FRANCHISE_ID", referencedColumnName = "FRANCHISE_ID")
    private List<HubUser> hubUsers = new ArrayList<>();

    @OneToMany
    @JoinColumn(name = "FRANCHISE_ID", referencedColumnName = "FRANCHISE_ID")
    private List<HubEvent> hubEvents = new ArrayList<>();

    /**
     * A simple default constructor for the Franchise class.
     */
    Franchise(){
        isActive = true;
    }

    /**
     * Getters and setters for the Franchise class.
     */
    public Integer getFrID() {
        return frID;
    }

    public void setFrID(Integer frID) {
        this.frID = frID;
    }

    public String getFrName() {
        return frName;
    }

    public void setFrName(String frName) {
        this.frName = frName;
    }

    public String getFrLocation() {
        return frLocation;
    }

    public void setFrLocation(String frLocation) {
        this.frLocation = frLocation;
    }

    @JsonIgnore
    public List<HubUser> getHubUsers() {
        return hubUsers;
    }

    @JsonProperty
    public void setHubUsers(List<HubUser> hubUsers) {
        this.hubUsers = hubUsers;
    }

    @JsonIgnore
    public List<HubEvent> getHubEvents() {
        return hubEvents;
    }

    @JsonProperty
    public void setHubEvents(List<HubEvent> hubEvents) {
        this.hubEvents = hubEvents;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }
}
